### ISSUE TITLE
Support Link tags with content and no href

### ISSUE THREAD

**Issue by wilkie** [hotsh/ostatus#4]
<link> tags may either encode the url in an href, or within the body of the tag. The OStatus code looks for an href attribute value as opposed to the latter. Although these types of links are annoying and not correct according to the Atom specification, we still see them. This may also be an ratom bug, but since the semantics of <Link> are a little out of scope for ratom, the fix should be within this gem instead.

This contributes to https://github.com/hotsh/rstat.us/issues/458 on rstat.us.

Code in question: https://github.com/hotsh/ostatus/blob/master/lib/ostatus/entry.rb#L50

Discovered by @clnclarinet, who writes:

> From https://identi.ca/api/statuses/user_timeline/55937.atom?max_id=89098925, the XML for the RT entry has:

```
<link rel="alternate" type="text/html">http://identi.ca/notice/89057569</link>
```

> So links.alternate would get this link, but this link's href would be nil.

**Comment by carols10cents** [comment]
This should have been closed when that commit was merged... this issue was fixed then.
